In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__


'2.4.1'

In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [3]:
# Encoding categorical data
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)


[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [4]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [5]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [7]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [8]:
X_test

array([[-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  1.61255917]])

In [9]:
# Initializing the ANN
ann = tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


In [10]:
# Training the ANN

# Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 350us/step - loss: 0.6176 - accuracy: 0.7000
Epoch 2/100
250/250 [==============================] - 0s 318us/step - loss: 0.4753 - accuracy: 0.7965
Epoch 3/100
250/250 [==============================] - 0s 326us/step - loss: 0.4707 - accuracy: 0.7897
Epoch 4/100
250/250 [==============================] - 0s 334us/step - loss: 0.4409 - accuracy: 0.7999
Epoch 5/100
250/250 [==============================] - 0s 326us/step - loss: 0.4412 - accuracy: 0.7958
Epoch 6/100
250/250 [==============================] - 0s 318us/step - loss: 0.4284 - accuracy: 0.7991
Epoch 7/100
250/250 [==============================] - 0s 314us/step - loss: 0.4392 - accuracy: 0.7914
Epoch 8/100
250/250 [==============================] - 0s 314us/step - loss: 0.4220 - accuracy: 0.8015
Epoch 9/100
250/250 [==============================] - 0s 322us/step - loss: 0.4223 - accuracy: 0.8049
Epoch 10/100
250/250 [==============================] - 0s 322us/step - l

250/250 [==============================] - 0s 330us/step - loss: 0.3405 - accuracy: 0.8571
Epoch 80/100
250/250 [==============================] - 0s 322us/step - loss: 0.3414 - accuracy: 0.8561
Epoch 81/100
250/250 [==============================] - 0s 322us/step - loss: 0.3318 - accuracy: 0.8619
Epoch 82/100
250/250 [==============================] - 0s 334us/step - loss: 0.3317 - accuracy: 0.8633
Epoch 83/100
250/250 [==============================] - 0s 326us/step - loss: 0.3428 - accuracy: 0.8600
Epoch 84/100
250/250 [==============================] - 0s 330us/step - loss: 0.3452 - accuracy: 0.8585
Epoch 85/100
250/250 [==============================] - 0s 334us/step - loss: 0.3444 - accuracy: 0.8548
Epoch 86/100
250/250 [==============================] - 0s 326us/step - loss: 0.3350 - accuracy: 0.8664
Epoch 87/100
250/250 [==============================] - 0s 330us/step - loss: 0.3326 - accuracy: 0.8624
Epoch 88/100
250/250 [==============================] - 0s 326us/step - loss:

In [17]:
# Predicting the result of a single observation

# Homework:
#Use our ANN model to predict if the customer with the following informations will leave the bank: 
#Geography: France
#Credit Score: 600
#Gender: Male
#Age: 40 years old
#Tenure: 3 years
#Balance: $ 60000
#Number of Products: 2
#Does this customer have a credit card? Yes
#Is this customer an Active Member: Yes
#Estimated Salary: $ 50000
#So, should we say goodbye to that customer?
#Making the predictions and evaluating the model

print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [19]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1504   91]
 [ 188  217]]


0.8605