# Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


# Importing the dataset

In [2]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [5]:
print(X_train)

[[    37  79000]
 [    37  71000]
 [    27 137000]
 [    35  22000]
 [    40  75000]
 [    47  34000]
 [    31  18000]
 [    38 113000]
 [    48  74000]
 [    35  47000]
 [    23  63000]
 [    35  75000]
 [    26  72000]
 [    42  65000]
 [    31  34000]
 [    47  47000]
 [    40  71000]
 [    41  59000]
 [    57  33000]
 [    35  50000]
 [    39  96000]
 [    35  38000]
 [    26  86000]
 [    22  63000]
 [    51 146000]
 [    39  79000]
 [    42  75000]
 [    39  42000]
 [    41  45000]
 [    47  20000]
 [    35  88000]
 [    40 142000]
 [    56  60000]
 [    36 125000]
 [    24  55000]
 [    46  74000]
 [    54  70000]
 [    35  72000]
 [    40  57000]
 [    48  96000]
 [    42 104000]
 [    36 144000]
 [    30  87000]
 [    40  60000]
 [    24  19000]
 [    58 144000]
 [    26  81000]
 [    19  26000]
 [    49  28000]
 [    44 139000]
 [    47  30000]
 [    41  63000]
 [    58  38000]
 [    39  71000]
 [    25  90000]
 [    48  35000]
 [    41  30000]
 [    29  75000]
 [    31  6600

In [6]:
print(X_test)

[[    32 135000]
 [    41  87000]
 [    60  42000]
 [    52  38000]
 [    26  30000]
 [    30  15000]
 [    30  79000]
 [    25  79000]
 [    56 104000]
 [    39  75000]
 [    28  79000]
 [    19  25000]
 [    26  17000]
 [    50  36000]
 [    37  62000]
 [    48 138000]
 [    42  54000]
 [    21  72000]
 [    57  74000]
 [    35  77000]
 [    30  62000]
 [    54 108000]
 [    37  75000]
 [    35  50000]
 [    42  65000]
 [    45  79000]
 [    37  33000]
 [    41  51000]
 [    48  33000]
 [    39  71000]
 [    29  80000]
 [    39 122000]
 [    42 108000]
 [    27  58000]
 [    38  80000]
 [    31  68000]
 [    36 126000]
 [    36  99000]
 [    60  34000]
 [    47 107000]
 [    35  57000]
 [    19  21000]
 [    49  65000]
 [    35  61000]
 [    27  89000]
 [    39 134000]
 [    28  59000]
 [    23  66000]
 [    40  65000]
 [    35  65000]
 [    54 104000]
 [    48  29000]
 [    37 144000]
 [    34  43000]
 [    26  43000]
 [    45  32000]
 [    57  60000]
 [    24  84000]
 [    26  3200

In [9]:
print(y_test)

[1 1 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1
 1 1 1 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 0 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 0
 1 0 0 0 1 0]


In [10]:
print(y_train)

[1 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 0 0 1
 0 0 1 1 1 0 0 0 1 0 0 1 1 1 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0
 1 1 1 0 1 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 1 0 0 0 0 0 0 1 0 1
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0
 0 0 1 0 1 0 1 0 1 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 1 0 0
 0 0 1 0 1 0 0 0 1 0 0 1 1 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1
 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0
 1 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 1 0 1
 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1]


# Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[-0.04544451  0.26293061]
 [-0.04544451  0.03186217]
 [-1.00850695  1.93817676]
 [-0.238057   -1.383432  ]
 [ 0.24347422  0.14739639]
 [ 0.91761793 -1.03682934]
 [-0.62328197 -1.49896621]
 [ 0.05086174  1.24497146]
 [ 1.01392418  0.11851283]
 [-0.238057   -0.66134314]
 [-1.39373193 -0.19920626]
 [-0.238057    0.14739639]
 [-1.1048132   0.06074573]
 [ 0.43608671 -0.14143916]
 [-0.62328197 -1.03682934]
 [ 0.91761793 -0.66134314]
 [ 0.24347422  0.03186217]
 [ 0.33978047 -0.31474048]
 [ 1.88068038 -1.0657129 ]
 [-0.238057   -0.57469247]
 [ 0.14716798  0.75395103]
 [-0.238057   -0.92129512]
 [-1.1048132   0.46511549]
 [-1.49003817 -0.19920626]
 [ 1.30284291  2.19812875]
 [ 0.14716798  0.26293061]
 [ 0.43608671  0.14739639]
 [ 0.14716798 -0.80576091]
 [ 0.33978047 -0.71911024]
 [ 0.91761793 -1.4411991 ]
 [-0.238057    0.5228826 ]
 [ 0.24347422  2.08259453]
 [ 1.78437413 -0.28585693]
 [-0.14175075  1.59157411]
 [-1.29742569 -0.4302747 ]
 [ 0.82131169  0.11851283]
 [ 1.59176164  0.00297862]
 

# Training the Naive Bayes model on the Training set

In [13]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train, y_train)

GaussianNB()

# Predicting a new result


In [15]:
print(clf.predict(sc.transform([[40,90000]])))

[0]


# Predicting the Test set results

In [17]:
y_pred = clf.predict(X_test)

In [18]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]]


# Making the Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[45  2]
 [ 6 27]]


0.9