# Importing Numpy Library


In [ ]:
import numpy as np

In [17]:
a = np.random.randint(10, size=(3, 3))

In [18]:
a

array([[2, 6, 5],
       [2, 3, 6],
       [6, 3, 4]])

In [19]:
b = np.random.randint(20, size=(3, 3))

In [20]:
b

array([[ 9,  1,  3],
       [ 1, 12,  2],
       [ 3, 18,  0]])

# Transpose Of Matrix

In [21]:
print(a.T)


[[2 2 6]
 [6 3 3]
 [5 6 4]]


In [22]:
print(b.T)

[[ 9  1  3]
 [ 1 12 18]
 [ 3  2  0]]


# Addition Of 2 Matrix

In [23]:
c = a + b
c

array([[11,  7,  8],
       [ 3, 15,  8],
       [ 9, 21,  4]])

# Subtraction of 2 Matrix

In [24]:
d = a - b
d

array([[ -7,   5,   2],
       [  1,  -9,   4],
       [  3, -15,   4]])

# Multiplication of 2 Numbers

In [25]:
e = a*b
e

array([[18,  6, 15],
       [ 2, 36, 12],
       [18, 54,  0]])